# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('aspect_ratio', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('tire_brand', models.CharField(max_length=256)),
                ('tire_model', models.CharField(max_length=256)),
                ('production_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('production_year', models.IntegerField()),
                ('season_type', models.IntegerField(choices=[(1, 'Summer'), (2, 'Winter'), (3, 'All-Season')], verbose_name='Which season ?')),
                ('type_of_load', models.IntegerField(choices=[(1, 'Normall'), (2, 'Cargo')], verbose_name='Load')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tire',
                'verbose_name_plural': 'Tires',
            },
        ),
    ]
