# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='image',
            field=models.ImageField(blank=True, upload_to='tire_image'),
        ),
    ]
