# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tires_shop', '0002_tires_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsDescribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('price_group', models.IntegerField(choices=[(1, 'budget'), (2, 'middle'), (3, 'premium'), (4, 'other')], verbose_name='Price group')),
                ('describe', models.TextField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires_shop.Tires')),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'verbose_name': 'Brand',
            },
        ),
    ]
